[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
bevy_quinnet = { workspace = true}
protocol = { path = "../protocol"}
world = { path = "../plugins/world"}
ping = { path = "../plugins/ping"}

