[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
bevy_quinnet = { workspace = true}
bevy_skein = { workspace = true}
bevy_remote = "0.16.1"
protocol = { path = "../protocol"}
ping = { path = "../plugins/ping"}

