[workspace]
resolver = "2"
members = [
    "client",
    "server",
    "protocol",
    "plugins/ping",
    "plugins/world",
]

[workspace.dependencies]
bevy = "0.16.1"
bevy_quinnet = "0.17.0"
serde = { version = "1.0.219", features = ["derive"] }
